### ISSUE TITLE
build Waffle: cannot load embed: malformed module path "embed": missing dot in first path element

### ISSUE THREAD

**Issue by kokkermanz** [Eeveelution/Waffle#1]
i seem to be getting this error when trying to build this project;
`build Waffle: cannot load embed: malformed module path "embed": missing dot in first path element`

**Comment by Eeveelution** [comment]
Can't replicate it myself, from googling I found out that this may be because you're running an outdated version of Go, you need at least Go 1.16 to be able to use embeds, and I'm using Go 1.18 to develop this.
