### ISSUE TITLE
Failed to Fetch User from Database, MySQL query failed.

### ISSUE THREAD

**Issue by Zordon1337** [Eeveelution/Waffle#9]
![image](https://user-images.githubusercontent.com/65111609/176889798-6daeb54d-1750-4a83-aea3-181700ba5e78.png)

**Comment by Zordon1337** [comment]
when i want import database i get
![image](https://user-images.githubusercontent.com/65111609/176891516-42c66774-9934-41d7-bb66-b2bf91116f9d.png)

**Comment by Eeveelution** [comment]
you're meant to use actual MySQL for this, and stop posting issues in every single old osu server you can find. fuck off

**Comment by pscr00ge** [comment]
lmfao

**Comment by Lekuruu** [comment]
yoo lmaoo

**Comment by Zordon1337** [comment]
> yoo lmaoo
noooo i feel bad for furball now
